# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestOpanki():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_opanki(self):
    self.driver.get("http://selenium1py.pythonanywhere.com/ru/accounts/login/")
    self.driver.set_window_size(1320, 682)
    self.driver.find_element(By.ID, "id_registration-email").click()
    self.driver.find_element(By.ID, "id_registration-email").send_keys("123@123")
    self.driver.find_element(By.ID, "id_registration-password1").click()
    self.driver.find_element(By.ID, "id_registration-password1").send_keys("123")
    self.driver.find_element(By.ID, "id_registration-password1").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "id_registration-password2").send_keys("123")
    self.driver.find_element(By.ID, "id_registration-password2").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".alert > strong")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".alert > strong")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".alert > strong").text == "Опаньки! Мы нашли какие-то ошибки"
  
